### ISSUE TITLE
ERR_REQUIRE_ESM error

### ISSUE THREAD

**Issue by AI-zik** [jerryOluranti/logie#4]
There's this error whenever I try to use logie in my projects.
The stack error in full:

`           return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module \node_modules\chalk\source\index.js from \node_modules\logie\dist\utils\paint.js not supported.
Instead change the require of index.js in projectDir\node_modules\logie\dist\utils\paint.js to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (\node_modules\ts-node\dist\index.js:851:20)
    at Object.<anonymous> (\node_modules\logie\dist\utils\paint.js:5:41)
    at Object.require.extensions.<computed> [as .js] (\node_modules\ts-node\dist\index.js:851:20)
    at Object.<anonymous> (\node_modules\logie\dist\logger\index.js:7:17)
    at Object.require.extensions.<computed> [as .js] (\node_modules\ts-node\dist\index.js:851:20)
    at Object.<anonymous> (\node_modules\logie\dist\index.js:53:22)
    at Object.require.extensions.<computed> [as .js] (\node_modules\ts-node\dist\index.js:851:20)
    at Object.<anonymous> (\index.ts:6:13)    at Module.m._compile (\node_modules\ts-node\dist\index.js:857:29)
    at Object.require.extensions.<computed> [as .ts] (\node_modules\ts-node\dist\index.js:859:16)
    at phase4 (\node_modules\ts-node\dist\bin.js:466:20)
    at bootstrap (\node_modules\ts-node\dist\bin.js:54:12)
    at main (\node_modules\ts-node\dist\bin.js:33:12)
    at Object.<anonymous> (project\node_modules\ts-node\dist\bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}`

**Comment by jerryOluranti** [comment]
Issue was caused by the ansi-styles package on which chalk library depends.

I have bumped ansi-styles to a commonjs supported version and removed the calk library entirely.

Kindly upgrade to version (^1.0.6) to prevent/resolve this issue.

Happy hacking  😇
